spring:
  #mysql
  datasource:
    url: jdbc:mysql://vmhost:3306/shiro_test?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #redis
  redis:
    host: vmhost
    port: 6379
    database: 0
    timeout: 30000
    password: '1234567'
token:
  refresh:
    interval: 3600
